apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: chart-paper-server
  name: chart-paper-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chart-paper-server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: chart-paper-server
    spec:
      containers:
      - image: ashupednekar535/chartpaper-server
        name: chartpaper-chart-paper-server
        env:
          - name: "DATABASE_URL"
            valueFrom:
              secretKeyRef:
                name: db-pguser-db
                key: pgbouncer-uri
        resources: {}
