apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: chart-paper-ui
  name: chart-paper-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chart-paper-ui
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: chart-paper-ui
    spec:
      containers:
      - image: ashupednekar535/chartpaper-ui
        name: chartpaper-chart-paper-ui
        resources: {}
status: {}
