apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: chart-paper-ui
  name: chart-paper-ui
spec:
  replicas: {{.Values.ui.replicas}}
  selector:
    matchLabels:
      app: chart-paper-ui
  template:
    metadata:
      labels:
        app: chart-paper-ui
    spec:
      containers:
      {{- $image := printf "%s/%s:%s" .Values.image.registry .Values.image.repository .Values.image.tag -}}
      - image: {{$image}} 
        name: chartpaper-chart-paper-ui
        resources: {}
        {{- if .Values.server.probes.enabled}}
        {{- end}}
status: {}
