version: '3.8'

services:
  backend:
    image: ashupednekar535/chartpaper-server
    container_name: chartpaper-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - chartpaper-data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro  # For Docker registry access
    environment:
      - GIN_MODE=release
      - DB_PATH=/data/charts.db
      - PORT=8000
    networks:
      - chartpaper-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: ashupednekar535/chartpaper-ui
    container_name: chartpaper-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - chartpaper-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  chartpaper-data:
    driver: local

networks:
  chartpaper-network:
    driver: bridge
