FROM node:18-alpine AS builder

RUN npm install -g typescript
RUN npm install -g vite 
WORKDIR /app

COPY package*.json ./

RUN npm ci #--only=production

COPY . .

RUN npm run build

FROM nginx:alpine

RUN mkdir /usr/share/nginx/html/chartpaper

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist/ /usr/share/nginx/html/chartpaper/
RUN ls /usr/share/nginx/html/chartpaper/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
