FROM node:18-alpine AS builder

RUN npm install -g typescript
RUN npm install -g vite 
WORKDIR /app

COPY package*.json ./

RUN npm ci #--only=production

COPY . .

RUN npm run build

FROM openresty/openresty:alpine

COPY nginx.conf /usr/local/openresty/nginx/conf/nginx.conf
RUN mkdir /usr/local/openresty/nginx/html/chartpaper/
COPY --from=builder /app/dist/ /usr/local/openresty/nginx/html/chartpaper/
RUN ls /usr/share/nginx/html/chartpaper/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

