#FROM golang:1.24-alpine AS builder
FROM crazymax/goxx AS builder

WORKDIR /app

COPY go.mod .

RUN git clone https://github.com/ashupednekar/compose ../temp-compose
RUN go mod download

COPY . .

RUN CGO_ENABLED=1 GOOS=linux go build -a -installsuffix cgo -o main ./cmd

FROM alpine:latest

RUN apk --no-cache add ca-certificates sqlite

WORKDIR /root/

COPY --from=builder /app/main .

RUN mkdir -p /data

EXPOSE 8000

ENV GIN_MODE=release

CMD ["./main"]
