version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: chartpaper-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=chartpaper
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - chartpaper-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d chartpaper"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ashupednekar535/chartpaper-server
    container_name: chartpaper-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - GIN_MODE=release
      - DATABASE_URL=postgres://user:password@postgres:5432/chartpaper?sslmode=disable
      - PORT=8000
    networks:
      - chartpaper-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: ashupednekar535/chartpaper-ui
    container_name: chartpaper-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - chartpaper-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres-data:
    driver: local

networks:
  chartpaper-network:
    driver: bridge
