server:
  replicas: 1
  image: 
    registry: docker.io
    repository: ashupednekar535/chartpaper-server
    tag: latest
  db:
    secret: db-pguser-db
    key: pgbouncer-uri
  probes:
    enabled: false
ui:
  replicas: 1
  image: 
    registry: docker.io
    repository: ashupednekar535/chartpaper-ui
    tag: latest
  probes:
    enabled: false
ingress:
  host: tools.ashudev.in
  issuer: letsencrypt
