// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type App struct {
	ID        int64          `json:"id"`
	ChartID   int64          `json:"chart_id"`
	Name      string         `json:"name"`
	Image     sql.NullString `json:"image"`
	AppType   sql.NullString `json:"app_type"`
	Ports     sql.NullString `json:"ports"`
	Configs   sql.NullString `json:"configs"`
	Mounts    sql.NullString `json:"mounts"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Chart struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Version     string         `json:"version"`
	Description sql.NullString `json:"description"`
	Type        string         `json:"type"`
	ChartUrl    string         `json:"chart_url"`
	ImageTag    sql.NullString `json:"image_tag"`
	CanaryTag   sql.NullString `json:"canary_tag"`
	Manifest    sql.NullString `json:"manifest"`
	IsLatest    sql.NullBool   `json:"is_latest"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type ChartVersion struct {
	Name        string         `json:"name"`
	Version     string         `json:"version"`
	Description sql.NullString `json:"description"`
	Type        string         `json:"type"`
	ChartUrl    string         `json:"chart_url"`
	ImageTag    sql.NullString `json:"image_tag"`
	CanaryTag   sql.NullString `json:"canary_tag"`
	IsLatest    sql.NullBool   `json:"is_latest"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Dependency struct {
	ID                int64          `json:"id"`
	ChartID           int64          `json:"chart_id"`
	DependencyName    string         `json:"dependency_name"`
	DependencyVersion string         `json:"dependency_version"`
	Repository        sql.NullString `json:"repository"`
	ConditionField    sql.NullString `json:"condition_field"`
	CreatedAt         sql.NullTime   `json:"created_at"`
}
