// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registry_configs.sql

package db

import (
	"context"
)

const getDefaultRegistryConfig = `-- name: GetDefaultRegistryConfig :one
SELECT id, name, registry_url, username, password, is_default, created_at, updated_at FROM registry_configs WHERE is_default = TRUE LIMIT 1
`

func (q *Queries) GetDefaultRegistryConfig(ctx context.Context) (RegistryConfig, error) {
	row := q.db.QueryRow(ctx, getDefaultRegistryConfig)
	var i RegistryConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RegistryUrl,
		&i.Username,
		&i.Password,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
